version: "2.1"

services:
  usershub:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.local
    volumes:
      - "$PWD/.:/UsersHub"
    expose:
      - "80"
    networks:
      databases:
      web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usershub.rule=Host(`${HOST}`) && PathPrefix(`${USERSHUB_PATH}`)"
      - "traefik.http.routers.usershub.entrypoints=web"

networks:
  web:
    external: true
  databases:
    external: true
